fileVersion: 1
id: a3d87eb5-609c-46ce-b06a-bfdb77d28943
name: USER_SECURITY
operation:
  database: ""
  dataset: ""
  deployEnabled: true
  description: ""
  locationName: INPUT
  metadata:
    columns:
      - acceptedValues:
          strictMatch: true
          values: []
        appliedColumnTests: {}
        columnReference:
          columnCounter: 739ffea7-d204-400d-90c2-f7b584e2829b
          stepCounter: a3d87eb5-609c-46ce-b06a-bfdb77d28943
        config: {}
        dataType: VARCHAR(16777216)
        defaultValue: ""
        description: ""
        name: LOGIN_NAME
        nullable: true
        primaryKey: false
        uniqueKey: false
      - acceptedValues:
          strictMatch: true
          values: []
        appliedColumnTests: {}
        columnReference:
          columnCounter: b2260e6b-c359-403b-a302-bbfeadc2392f
          stepCounter: a3d87eb5-609c-46ce-b06a-bfdb77d28943
        config: {}
        dataType: VARCHAR(16777216)
        defaultValue: ""
        description: ""
        name: LEVEL1_DESC
        nullable: true
        primaryKey: false
        uniqueKey: false
      - acceptedValues:
          strictMatch: true
          values: []
        appliedColumnTests: {}
        columnReference:
          columnCounter: e706da4d-8209-4f40-b296-448fb320868c
          stepCounter: a3d87eb5-609c-46ce-b06a-bfdb77d28943
        config: {}
        dataType: VARCHAR(16777216)
        defaultValue: ""
        description: ""
        name: LEVEL2_DESC
        nullable: true
        primaryKey: false
        uniqueKey: false
      - acceptedValues:
          strictMatch: true
          values: []
        appliedColumnTests: {}
        columnReference:
          columnCounter: 06399f6f-8453-492c-8075-341d68d4465f
          stepCounter: a3d87eb5-609c-46ce-b06a-bfdb77d28943
        config: {}
        dataType: VARCHAR(16777216)
        defaultValue: ""
        description: ""
        name: LEVEL3_DESC
        nullable: true
        primaryKey: false
        uniqueKey: false
      - acceptedValues:
          strictMatch: true
          values: []
        appliedColumnTests: {}
        columnReference:
          columnCounter: f40d3613-7c1b-4824-a05a-a7b6a4627add
          stepCounter: a3d87eb5-609c-46ce-b06a-bfdb77d28943
        config: {}
        dataType: VARCHAR(16777216)
        defaultValue: ""
        description: ""
        name: LEVEL4_DESC
        nullable: true
        primaryKey: false
        uniqueKey: false
      - acceptedValues:
          strictMatch: true
          values: []
        appliedColumnTests: {}
        columnReference:
          columnCounter: d53396e5-b00c-4977-9829-5579c8fd34e3
          stepCounter: a3d87eb5-609c-46ce-b06a-bfdb77d28943
        config: {}
        dataType: VARCHAR(16777216)
        defaultValue: ""
        description: ""
        name: BRAND
        nullable: true
        primaryKey: false
        uniqueKey: false
    join:
      joinCondition: FROM {{ ref('INPUT', 'USER_SECURITY') }}
  name: USER_SECURITY
  schema: ""
  sqlType: Source
  table: USER_SECURITY
  type: sourceInput
  version: 1
type: Node
